export const fakeData = [
  {
    id: 1,
    name: "علی رضایی",
    email: "ali.rezaei@gmail.com",
    job: "توسعه‌دهنده فرانت‌اند",
    phone: "09124567891",
    isSelected: false,
  },
  {
    id: 2,
    name: "سارا محمدی",
    email: "sara.mohammadi@gmail.com",
    job: "طراح UI/UX",
    phone: "09351234567",
    isSelected: false,
  },
  {
    id: 3,
    name: "مهدی کاظمی",
    email: "mehdi.kazemi@gmail.com",
    job: "برنامه‌نویس بک‌اند",
    phone: "09217894563",
    isSelected: false,
  },
  {
    id: 4,
    name: "زهرا حسینی",
    email: "zahra.hosseini@gmail.com",
    job: "تحلیلگر داده",
    phone: "09139876542",
    isSelected: false,
  },
  {
    id: 5,
    name: "امیرحسین احمدی",
    email: "amir.ahmadi@gmail.com",
    job: "مهندس نرم‌افزار",
    phone: "09913456782",
    isSelected: false,
  },
  {
    id: 6,
    name: "نگین کریمی",
    email: "negin.karimi@gmail.com",
    job: "تستر نرم‌افزار",
    phone: "09021239876",
    isSelected: false,
  },
  {
    id: 7,
    name: "رضا شریفی",
    email: "reza.sharifi@gmail.com",
    job: "مدیر پروژه",
    phone: "09126789034",
    isSelected: false,
  },
  {
    id: 8,
    name: "الهام جعفری",
    email: "elham.jafari@gmail.com",
    job: "تولیدکننده محتوا",
    phone: "09307894561",
    isSelected: false,
  },
  {
    id: 9,
    name: "پویا نادری",
    email: "pooya.naderi@gmail.com",
    job: "برنامه‌نویس موبایل",
    phone: "09204567812",
    isSelected: false,
  },
  {
    id: 10,
    name: "مریم قربانی",
    email: "maryam.ghorbani@gmail.com",
    job: "کارشناس دیجیتال مارکتینگ",
    phone: "09135678904",
    isSelected: false,
  },
];
